// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkzygwpfyxfoekeuryyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrenlnd3BmeXhmb2VrZXVyeXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODUyNTksImV4cCI6MjA2OTI2MTI1OX0.dVQcWfdax89quiAF5CVvi1PSLiFd_woA3L0hZhRK5i8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});